server:
  port: 9999

print:
  settings:
    enable: false
    bdBaseUrl: 47.106.243.154:9001
    zqBaseUrl: 47.106.243.154:9016
    lgBaseUrl: 218.17.60.162:10052
    hnBaseUrl: 183.62.200.242:82
    fyBaseUrl: 61.145.158.182:10082
    smBaseUrl: 120.78.226.92:18002
    bdrmBaseUrl: 39.107.78.98:6049
    fileLocation: C:\spd-print
    lowValueTagDir: lowValueTagPdfs

notify:
  wx-pusher:
    wx-pusher-baseurl:
    wx-pusher-spt:

