package com.spd.print;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class SpdPrintApplicationTests {

    @Test
    void contextLoads() {
        String str = "IFACE_ID\tOPERATING_UNIT\tINVOICE_TYPE\tVENDOR_NUMBER\tVENDOR_NAME\tVENDOR_SITE_CODE\tINVOICE_DATE\tGL_DATE\tINVOICE_NUM\tSUPPLIER_TAX_INVOICE_NUMBER\tATTACHMENT_NUM\tINVOICE_AMOUNT\tACTION_TYPE\tOPERATING_BY\tSYNC_DATE\tPROCESS_FLAG\tPROCESS_DATE\tERROR_MESSAGE\tATTRIBUTE1\tATTRIBUTE2\tATTRIBUTE3\tATTRIBUTE4\tATTRIBUTE5\tATTRIBUTE6\tATTRIBUTE7\tATTRIBUTE8\tATTRIBUTE9\tATTRIBUTE10\tATTRIBUTE11\tATTRIBUTE12\tATTRIBUTE13\tATTRIBUTE14\tATTRIBUTE15\tSPD_CREATE_TIME\tSPD_CREATE_MAN\tSPD_STATE\tSPD_SEND_TIME\tSPD_SEND_NAME";
        System.out.println(str.replace("\t",","));
    }

}
